# Generated by Django 4.0.5 on 2022-06-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('identidad', models.CharField(choices=[('Profesor Jefe', 'Profesor Jefe'), ('Profesor de Asignatura', 'Profesor de Asignatura')], max_length=255, null=True)),
            ],
        ),
    ]
