# Generated by Django 4.0.4 on 2022-06-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cursa_alumno_cursa_curso_detalle_evaluacion_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFESOR',
            fields=[
                ('rut_profesor', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_profesor', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_profesor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE_JEFATURA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURSO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('PROFESOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profesor')),
            ],
        ),
    ]
